export const ALL_FORMS_REQUEST = "ALL_FORMS_REQUEST";
export const ALL_FORMS_SUCCESS = "ALL_FORMS_SUCCESS";
export const ALL_FORMS_FAILURE = "ALL_FORMS_FAILURE";

export const ADD_FORM_REQUEST = "ADD_FORM_REQUEST";
export const ADD_FORM_SUCCESS = "ADD_FORM_SUCCESS";
export const ADD_FORM_FAILURE = "ADD_FORM_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
